### ISSUE TITLE
Issue of prediction input Label

### ISSUE THREAD

**Issue by kanyuanhao** [DaniTheOrange/EPIC-TRACE#1]
Hi,

I would like to know how do I set the "Label" column of the input csv of test_results.py. Since I am using it for prediction, I am not supposed to have the label already?

**Comment by DaniTheOrange** [comment]
Hi,
Currently the Dataloader requires the Label so the easiest solution is to put any number (e.g. all 1) for the values of the columns. Hope this helps.

**Comment by kanyuanhao** [comment]
Thank you a lot!
